# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editonsetsui.ui'
#
# Created: Wed Sep 15 10:13:23 2010
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1042, 854)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.onset_number = QtGui.QSpinBox(self.centralwidget)
        self.onset_number.setEnabled(False)
        self.onset_number.setGeometry(QtCore.QRect(890, 420, 51, 25))
        self.onset_number.setMinimum(1)
        self.onset_number.setMaximum(1)
        self.onset_number.setProperty("value", 1)
        self.onset_number.setObjectName("onset_number")
        self.db_path_label = QtGui.QLabel(self.centralwidget)
        self.db_path_label.setGeometry(QtCore.QRect(10, 490, 41, 16))
        self.db_path_label.setObjectName("db_path_label")
        self.db_path = QtGui.QLineEdit(self.centralwidget)
        self.db_path.setEnabled(False)
        self.db_path.setGeometry(QtCore.QRect(120, 490, 381, 22))
        self.db_path.setObjectName("db_path")
        self.type_label = QtGui.QLabel(self.centralwidget)
        self.type_label.setGeometry(QtCore.QRect(10, 530, 41, 31))
        self.type_label.setObjectName("type_label")
        self.type = QtGui.QComboBox(self.centralwidget)
        self.type.setGeometry(QtCore.QRect(120, 530, 381, 26))
        self.type.setObjectName("type")
        self.type.addItem("")
        self.type.addItem("")
        self.type.addItem("")
        self.type.addItem("")
        self.audio_display = QtGui.QGraphicsView(self.centralwidget)
        self.audio_display.setGeometry(QtCore.QRect(10, 10, 1021, 411))
        self.audio_display.setObjectName("audio_display")
        self.play = QtGui.QToolButton(self.centralwidget)
        self.play.setGeometry(QtCore.QRect(460, 420, 21, 21))
        self.play.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/Play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play.setIcon(icon)
        self.play.setIconSize(QtCore.QSize(32, 32))
        self.play.setObjectName("play")
        self.stop = QtGui.QToolButton(self.centralwidget)
        self.stop.setGeometry(QtCore.QRect(490, 420, 21, 21))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/Stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stop.setIcon(icon1)
        self.stop.setObjectName("stop")
        self.import_audio = QtGui.QToolButton(self.centralwidget)
        self.import_audio.setGeometry(QtCore.QRect(10, 420, 21, 21))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/Music.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.import_audio.setIcon(icon2)
        self.import_audio.setObjectName("import_audio")
        self.save = QtGui.QToolButton(self.centralwidget)
        self.save.setGeometry(QtCore.QRect(40, 420, 21, 21))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/Floppy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save.setIcon(icon3)
        self.save.setObjectName("save")
        self.new_onset = QtGui.QToolButton(self.centralwidget)
        self.new_onset.setGeometry(QtCore.QRect(950, 420, 21, 21))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/Write.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.new_onset.setIcon(icon4)
        self.new_onset.setCheckable(True)
        self.new_onset.setChecked(True)
        self.new_onset.setObjectName("new_onset")
        self.move_onset = QtGui.QToolButton(self.centralwidget)
        self.move_onset.setGeometry(QtCore.QRect(980, 420, 21, 21))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/spanner32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.move_onset.setIcon(icon5)
        self.move_onset.setCheckable(True)
        self.move_onset.setObjectName("move_onset")
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(505, 450, 21, 381))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 450, 81, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.delete_onset = QtGui.QToolButton(self.centralwidget)
        self.delete_onset.setGeometry(QtCore.QRect(1010, 420, 21, 21))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/Delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_onset.setIcon(icon6)
        self.delete_onset.setObjectName("delete_onset")
        self.size_label = QtGui.QLabel(self.centralwidget)
        self.size_label.setGeometry(QtCore.QRect(10, 610, 101, 16))
        self.size_label.setObjectName("size_label")
        self.size = QtGui.QLabel(self.centralwidget)
        self.size.setGeometry(QtCore.QRect(120, 610, 61, 16))
        self.size.setObjectName("size")
        self.sampling_rate_label = QtGui.QLabel(self.centralwidget)
        self.sampling_rate_label.setGeometry(QtCore.QRect(10, 640, 91, 16))
        self.sampling_rate_label.setObjectName("sampling_rate_label")
        self.sampling_rate = QtGui.QLabel(self.centralwidget)
        self.sampling_rate.setGeometry(QtCore.QRect(120, 640, 61, 16))
        self.sampling_rate.setObjectName("sampling_rate")
        self.num_onsets_label = QtGui.QLabel(self.centralwidget)
        self.num_onsets_label.setGeometry(QtCore.QRect(10, 670, 81, 16))
        self.num_onsets_label.setObjectName("num_onsets_label")
        self.num_onsets = QtGui.QLabel(self.centralwidget)
        self.num_onsets.setGeometry(QtCore.QRect(120, 670, 61, 16))
        self.num_onsets.setObjectName("num_onsets")
        self.back = QtGui.QToolButton(self.centralwidget)
        self.back.setGeometry(QtCore.QRect(430, 420, 21, 21))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/Back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back.setIcon(icon7)
        self.back.setObjectName("back")
        self.db_label = QtGui.QLabel(self.centralwidget)
        self.db_label.setGeometry(QtCore.QRect(750, 450, 62, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.db_label.setFont(font)
        self.db_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.db_label.setObjectName("db_label")
        self.db_files = QtGui.QListWidget(self.centralwidget)
        self.db_files.setGeometry(QtCore.QRect(530, 540, 501, 291))
        self.db_files.setAlternatingRowColors(True)
        self.db_files.setObjectName("db_files")
        self.comments_label = QtGui.QLabel(self.centralwidget)
        self.comments_label.setGeometry(QtCore.QRect(10, 700, 71, 16))
        self.comments_label.setObjectName("comments_label")
        self.comments = QtGui.QPlainTextEdit(self.centralwidget)
        self.comments.setGeometry(QtCore.QRect(120, 700, 381, 131))
        self.comments.setObjectName("comments")
        self.num_files_label = QtGui.QLabel(self.centralwidget)
        self.num_files_label.setGeometry(QtCore.QRect(540, 480, 61, 16))
        self.num_files_label.setObjectName("num_files_label")
        self.num_onsets_in_db_label = QtGui.QLabel(self.centralwidget)
        self.num_onsets_in_db_label.setGeometry(QtCore.QRect(540, 510, 81, 16))
        self.num_onsets_in_db_label.setObjectName("num_onsets_in_db_label")
        self.num_files = QtGui.QLabel(self.centralwidget)
        self.num_files.setGeometry(QtCore.QRect(640, 480, 61, 16))
        self.num_files.setObjectName("num_files")
        self.num_onsets_in_db = QtGui.QLabel(self.centralwidget)
        self.num_onsets_in_db.setGeometry(QtCore.QRect(640, 510, 61, 16))
        self.num_onsets_in_db.setObjectName("num_onsets_in_db")
        self.zoom_in = QtGui.QToolButton(self.centralwidget)
        self.zoom_in.setGeometry(QtCore.QRect(520, 420, 21, 21))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/ZoomIn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoom_in.setIcon(icon8)
        self.zoom_in.setObjectName("zoom_in")
        self.zoom_out = QtGui.QToolButton(self.centralwidget)
        self.zoom_out.setGeometry(QtCore.QRect(550, 420, 21, 21))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/icons/ZoomOut.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoom_out.setIcon(icon9)
        self.zoom_out.setObjectName("zoom_out")
        self.texture_label = QtGui.QLabel(self.centralwidget)
        self.texture_label.setGeometry(QtCore.QRect(10, 580, 61, 16))
        self.texture_label.setObjectName("texture_label")
        self.texture = QtGui.QComboBox(self.centralwidget)
        self.texture.setGeometry(QtCore.QRect(120, 570, 381, 26))
        self.texture.setObjectName("texture")
        self.texture.addItem("")
        self.texture.addItem("")
        self.delete_file = QtGui.QToolButton(self.centralwidget)
        self.delete_file.setGeometry(QtCore.QRect(1010, 520, 21, 21))
        self.delete_file.setIcon(icon6)
        self.delete_file.setObjectName("delete_file")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Edit Onsets", None, QtGui.QApplication.UnicodeUTF8))
        self.db_path_label.setText(QtGui.QApplication.translate("MainWindow", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.type_label.setText(QtGui.QApplication.translate("MainWindow", "Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.type.setItemText(0, QtGui.QApplication.translate("MainWindow", "Mixed", None, QtGui.QApplication.UnicodeUTF8))
        self.type.setItemText(1, QtGui.QApplication.translate("MainWindow", "Pitched Non-Percussive", None, QtGui.QApplication.UnicodeUTF8))
        self.type.setItemText(2, QtGui.QApplication.translate("MainWindow", "Pitched Percussive", None, QtGui.QApplication.UnicodeUTF8))
        self.type.setItemText(3, QtGui.QApplication.translate("MainWindow", "Non-Pitched Percussive", None, QtGui.QApplication.UnicodeUTF8))
        self.play.setToolTip(QtGui.QApplication.translate("MainWindow", "Play audio", None, QtGui.QApplication.UnicodeUTF8))
        self.stop.setToolTip(QtGui.QApplication.translate("MainWindow", "Stop audio", None, QtGui.QApplication.UnicodeUTF8))
        self.stop.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.import_audio.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.save.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.new_onset.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.move_onset.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Current File", None, QtGui.QApplication.UnicodeUTF8))
        self.delete_onset.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.size_label.setText(QtGui.QApplication.translate("MainWindow", "Size (samples):", None, QtGui.QApplication.UnicodeUTF8))
        self.size.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.sampling_rate_label.setText(QtGui.QApplication.translate("MainWindow", "Sampling rate:", None, QtGui.QApplication.UnicodeUTF8))
        self.sampling_rate.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.num_onsets_label.setText(QtGui.QApplication.translate("MainWindow", "No. Onsets:", None, QtGui.QApplication.UnicodeUTF8))
        self.num_onsets.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.back.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.db_label.setText(QtGui.QApplication.translate("MainWindow", "Database", None, QtGui.QApplication.UnicodeUTF8))
        self.db_files.setSortingEnabled(True)
        self.comments_label.setText(QtGui.QApplication.translate("MainWindow", "Comments:", None, QtGui.QApplication.UnicodeUTF8))
        self.num_files_label.setText(QtGui.QApplication.translate("MainWindow", "No. Files:", None, QtGui.QApplication.UnicodeUTF8))
        self.num_onsets_in_db_label.setText(QtGui.QApplication.translate("MainWindow", "No. Onsets:", None, QtGui.QApplication.UnicodeUTF8))
        self.num_files.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.num_onsets_in_db.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.zoom_in.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.zoom_out.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.texture_label.setText(QtGui.QApplication.translate("MainWindow", "Texture:", None, QtGui.QApplication.UnicodeUTF8))
        self.texture.setItemText(0, QtGui.QApplication.translate("MainWindow", "Monophonic", None, QtGui.QApplication.UnicodeUTF8))
        self.texture.setItemText(1, QtGui.QApplication.translate("MainWindow", "Polyphonic", None, QtGui.QApplication.UnicodeUTF8))
        self.delete_file.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))

import editonsets_rc
